#!/usr/bin/env php
<?php

/**
 * A cli tool that helps convert xml, json and yaml beetween each other
 */
error_reporting(E_STRICT);

define('ERROR_EXIT_CODE', 0);
define('OK_EXIT_CODE', 1);

require('./vendor/autoload.php');

use function Converter\createConverter;
use function Converter\convert;
use function Converter\getErrors;

if(count($argv) !== 3) {
    $errorMessage = 'Error!';
    if(count($argv) == 2) {
        $errorMessage .= ' Not enouth arguments.';
    } elseif(count($argv) > 3) {
        $errorMessage .= ' Too many arguments.';
    }
    echo $errorMessage . PHP_EOL;
    echo 'Usage example:' . PHP_EOL;
    echo '      convert from.yml to.json' . PHP_EOL;
    printUsage();
    exit(ERROR_EXIT_CODE);
}

list($scriptName, $input, $output) = $argv;

$converter = createConverter($input, $output);

if(!convert($converter)) {
    echo 'Error!' . PHP_EOL;
    echo implode(PHP_EOL, getErrors($converter));
    echo PHP_EOL;
    exit(ERROR_EXIT_CODE);
}

echo 'Done!' . PHP_EOL;
exit(OK_EXIT_CODE);
